jenkins:
  systemMessage: "Welcome to the Whanos project configured by Configuration as Code plugin"
  remotingSecurity:
    enabled: True
  securityRealm:
    local:
      allowSignup: false
      users:
        - id: "admin"
          name: "Admin"
          password: ${ADMIN_PASSWORD}
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Whanos admin"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"

unclassified:
  location:
    url: "http://localhost:8080/"
  security:
    scriptApproval:
      approvedSignatures:
        - "method java.lang.Process getInputStream"
        - "method java.lang.Process waitFor"
        - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods execute java.lang.String"

jobs:
  - file: /var/jenkins_home/job_dsl.groovy