jenkins:
  systemMessage: "Welcome to the Whanos project configured by Configuration as Code plugin"
  securityRealm:
    local:
      allowSignup: false
      users:
        - name: "Admin"
          id: "admin"
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            permissions:
              - "Overall/Administer"
            entries:
              - user: "admin"

jobs:
  - file: /var/jenkins_home/Jenkins/jobs.groovy