jenkins:
  systemMessage: "Welcome to the Whanos project configured by Configuration as Code plugin"
  remotingSecurity:
    enabled: True
  securityRealm:
    local:
      allowSignup: false
      users:
        - id: "admin"
          name: "Admin"
          password: ${ADMIN_PASSWORD}
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Whanos admin"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"

jobs:
  - file: /Jenkins/jobs.groovy