pipeline {
  agent any

  parameters {
    string(name: 'IMAGE_URL',   defaultValue: '')
    string(name: 'APP_NAME', defaultValue: '')
    string(name: 'HOST_NAME', defaultValue: '', description: "laisser vide pour APP_NAME.dop.io")
    text(  name: 'YAML_CONTENT', defaultValue: '', description: 'User YAML file')
  }

  environment {
    DEFAULT_REPLICAS = '1'
    DEFAULT_RESOURCE = ''
    DEFAULT_PORTS = ''
    HOST_NAME = "${params.HOST_NAME ?: "${params.APP_NAME}.dop.io"}"
  }

  stages {

    stage('Read and Save specs') {

      steps {
        sh '''#!/usr/bin/env bash
        
          set -euo pipefail

          #Replicas
          REPLICAS = $(printf '%s' "${YAML_CONTENT:-{}}" | yq '.deployment.replicas // 1' -)

          #Resources
          REQ_CPU = $(printf '%s' "${YAML_CONTENT:-{}}" | yq '.deployment.resources.requests.cpu // "100m"' -)
          REQ_MEM = $(printf '%s' "${YAML_CONTENT:-{}}" | yq '.deployment.resources.requests.memory // "128Mi"' -)
          LIM_CPU = $(printf '%s' "${YAML_CONTENT:-{}}" | yq '.deployment.resources.limits.cpu   // "500m"' -)
          LIM_MEM = $(printf '%s' "${YAML_CONTENT:-{}}" | yq '.deployment.resources.limits.memory // "256Mi"' -)

          RESOURCES_BLOCK = ""

          if [ -n "${REQ_CPU}${REQ_MEM}${LIM_CPU}${LIM_MEM}" ]; then
            printf -v RESOURCES_BLOCK '%s' "resources:\n"

            if [ -n "${REQ_CPU}${REQ_MEM}" ]; then
              printf -v RESOURCES_BLOCK '%s%s' "$RESOURCES_BLOCK" "requests:\n"
              [ -n "$REQ_CPU" ] && printf -v RESOURCES_BLOCK '%s%s' "$RESOURCES_BLOCK" "cpu: \"$REQ_CPU\"\n"
              [ -n "$REQ_MEM" ] && printf -v RESOURCES_BLOCK '%s%s' "$RESOURCES_BLOCK" "memory: \"$REQ_MEM\"\n"
            fi

            if [ -n "${LIM_CPU}${LIM_MEM}" ]; then
              printf -v RESOURCES_BLOCK '%s%s' "$RESOURCES_BLOCK" "            limits:\n"
              [ -n "$LIM_CPU" ] && printf -v RESOURCES_BLOCK '%s%s' "$RESOURCES_BLOCK" "cpu: \"$LIM_CPU\"\n"
              [ -n "$LIM_MEM" ] && printf -v RESOURCES_BLOCK '%s%s' "$RESOURCES_BLOCK" "memory: \"$LIM_MEM\"\n"
            fi

          fi

          #Ports
          PORTS_JSON = $(printf '%s' "${YAML_CONTENT:-{}}" | yq -o=json '.deployment.ports // []' -)

          FIRST_PORT = $(echo "$PORTS_JSON" | jq -r '.[0] // empty')

          mapfile -t PORTS < <(echo "$PORTS_JSON" | jq -r '.[]')

          PORTS_BLOCK = "$(
            for p in \"${PORTS[@]}\"; do
              printf \"\n- name: web-$p\nport: $p\"
            done
          )"

          #Enregistrement
          {
            printf 'REPLICAS=%s\n' "$REPLICAS"
            printf 'RESOURCES_BLOCK=%s\n' "$RESOURCES_BLOCK"
            printf 'FIRST_PORT=%s\n' "$FIRST_PORT"
            printf 'PORTS_BLOCK=%s\n' "$PORTS_BLOCK"
          } >> .build_env
        
        '''

      }

    }

    stage('Write specs in the duplicates files') {

      steps {

        source .build_env
        
        #Deployment
        cp template.deployment.yaml "${params.APP_NAME}.deployment.yaml"
        sed -i \
          -e "s|__APP_NAME__|${params.APP_NAME}|g" \
          -e "s|__IMAGE_URL__|${IMAGE}|g" \
          -e "s|__REPLICAS__|${REPLICAS}|g" \
          "${APP}.deployment.yaml"

        ${PORTS_BLOCK} ? sed -i "s|__PORTS__|${PORTS_BLOCK}|" "${params.APP_NAME}.deployment.yaml" : sed -i "/__PORTS__/d" "${params.APP_NAME}.deployment.yaml"

        ${RESOURCES_BLOCK} ? sed -i "s|__RESOURCES__|${RESOURCES_BLOCK}|" "${params.APP_NAME}.deployment.yaml" : sed -i "/__RESOURCES__/d" "${params.APP_NAME}.deployment.yaml"


        if [ -n "${PORTS_BLOCK}" ]; then

          #Ingress
          cp template.ingress.yaml "${params.APP_NAME}.ingress.yaml"

          #Service
          cp template.service.yaml "${params.APP_NAME}.service.yaml"

          #Traefik
          cp traefik.deployment.yaml "${params.APP_NAME}.traefik.deployment.yaml"
          cp traefik.rbac.yaml "${params.APP_NAME}.traefik.rbac.yaml"
          cp traefik.service.yaml "${params.APP_NAME}.traefik.service.yaml"

          // TODO: Remplir fichiers app-name.*.yaml
        fi

      }

    }

  }
}
